### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by lsolier** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#1]
I'm trying to run the RESTful service, however when I enter the url: http: // localhost: 8080 / cars; I get the following error: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data", noting in the raw data detail it shows me:

`<html> <body> <h1> Whitelabel Error Page </ h1> <p> This application has not explicit mapping for / error, so you are seeing this as a fallback. </ p> <div id = 'created' > Wed Jul 18 00:09:49 COT 2018 </ div> <div> There was an unexpected error (type = Internal Server Error, status = 500). </ Div> <div> Type definition error: [simple type, class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList [0] - & gt; com.packt.cardatabase.domain.Car [& quot; owner & quot;] - & gt; com.packt. cardatabase.domain.Owner _ $$ _ jvstbe3_1 [& quot; handler & quot;]) </ div> </ body> </ html> `

Please, could you help me find a solution?

**Comment by juhahinkula** [comment]
I will check this later during the weekend.

**Comment by lsolier** [comment]
I am in chapter 3 - page 58, I managed to execute it using the annotation `@JsonIgnore` in the file `Car.java`,

```
@Entity
public class Car {
@Id
@GeneratedValue (strategy = GenerationType.AUTO)
private long id;
private String brand, model, color, registerNumber;
private int year, price;

@ManyToOne (fetch = FetchType.LAZY)
@JoinColumn (name = "owner")
@JsonIgnore
private Owner owner;
```

However, I only print the list of cars, as the image shows: [](http://nube.inverdiro.com/index.php/s/pgonbNRcAosz7TT)

**Comment by juhahinkula** [comment]
That looks correct now. It now returns the list of cars in JSON.

**Comment by mydnite** [comment]
I get the same serializer error with my code, and have confirmed the same serializererror is present in the chapter 3 code in this Book's git repo.  I'm building tand running the code on ubuntu with java 1.8._171.

However if I also add "@JsonIgnore" to Car.java just above owner, as well as maintaining it above cars in Owner.java, I get the same list of cars output as above.

**Comment by mydnite** [comment]
Interestingly if I add null for the owners, I no longer get the serialization error, and get the following and expected output.

[{"brand":"Ford","model":"Mustang","color":"Red","registerNumber":"ADF-1121","year":2017,"price":59000,"owner":null},{"brand":"Nissan","model":"AAAAA","color":"Blue","registerNumber":"ABC-1234","year":2016,"price":22000,"owner":null},{"brand":"ZZZZ","model":"XXXXX","color":"Yellow","registerNumber":"DEF-0987","year":2015,"price":11000,"owner":null}]

**Comment by mydnite** [comment]
See the answer and class annotation in this stackoverflow article, adding the class annotation to the owner class resolved the serialization error for me.  The reasoning in the answer also makes a lot of sense to me.

See
https://stackoverflow.com/questions/24994440/no-serializer-found-for-class-org-hibernate-proxy-pojo-javassist-javassist

**Comment by juhahinkula** [comment]
Yes, thanks for the comments. I also get the same error and will fix that.

In this phase the REST api call is done to endpoint /api/cars because we are using Spring Data REST and that is working properly.

**Comment by juhahinkula** [comment]
Yes, @JsonIgnoreProperties annotation is the correct fix. Then you can access the owner also.

**Comment by lsolier** [comment]
Thank you very much, I managed to fix it by adding `@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})` .

PD. Good book. 👍
