### ISSUE TITLE
Chapter 4 Cannot Resolve empty AuthenticationFilter Constructor

### ISSUE THREAD

**Issue by caverdude** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#10]
https://imgur.com/a/L23L7gA

It looks like the api changed. 
https://docs.spring.io/spring-security/site/docs/5.2.1.BUILD-SNAPSHOT/api/org/springframework/security/web/authentication/AuthenticationFilter.html

What should I do now?

**Comment by caverdude** [comment]
@Override
    protected void configure(HttpSecurity http) throws Exception {
        http.csrf().disable().cors().and().authorizeRequests()
                .antMatchers(HttpMethod.POST, "/login").permitAll()
                .anyRequest().authenticated()
                .and()
                // Filter for the api/login requests
                .addFilterBefore(new LoginFilter("/login", authenticationManager()),
                        UsernamePasswordAuthenticationFilter.class)
                // Filter for other requests to check JWT in header
                .addFilterBefore(new AuthenticationFilter(),
                        UsernamePasswordAuthenticationFilter.class);
    }

**Comment by juhahinkula** [comment]
I also upgraded to Spring Boot 2.2.3 and security 5.2.1 and couldn't reproduce your error so there must be something wrong in your code.

**Comment by caverdude** [comment]
Yes, sorry, I somehow missed that class

**Comment by juhahinkula** [comment]
Thats ok
