### ISSUE TITLE
Chapter 3 #7. when I add @JsonIgnore I get error

### ISSUE THREAD

**Issue by caverdude** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#11]
https://pastebin.com/UR9cG1Hx

I changed @ManyToOne(fetch=FetchType.EAGER)  from LAZY and then get proper results.

**Comment by juhahinkula** [comment]
Could you push your code to Github and I can test it.

**Comment by caverdude** [comment]
https://imgur.com/8B0qID2

https://github.com/caverdude/javascript

line 12 in Car.java change LAZY to EAGER and it works. otherwise I get the error in the image above.
