### ISSUE TITLE
Chapter 10 react-table is now react-table-6

### ISSUE THREAD

**Issue by caverdude** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#14]
Not your fault but react-table won't work, says you can't import so you do
npm i  react-table-6 
and change imports to
import ReactTable from 'react-table-6';
import 'react-table-6/react-table.css';

and it workss

**Comment by juhahinkula** [comment]
Yes, thanks for the issue. React table component has upgraded to version 7 and the functionality is now based on hooks. To use version 6 you have to use install and import commands that you provided.
