### ISSUE TITLE
Chapter 4 memory user get No AuthenticationProvider found 

### ISSUE THREAD

**Issue by caverdude** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#15]
No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken

https://imgur.com/LLYSsUR

http://github.com/caverdude/java/
https://github.com/caverdude/java/blob/master/FullStackSpringBootReact-1-ch4-8.zip
The source is up to page 78, next is to delete userDetailsService() to disable in-memory user

**Comment by caverdude** [comment]
I got the name of one class wrong, Should have been UserDetailServiceImpl but after refactor didn't affect the problem

also should the class not be named UserDetailsServiceImpl

**Comment by gaurav-packt** [comment]
Please reopen if the issue persists.
