### ISSUE TITLE
Chapter 4 JWT MismatchedInputException: No content to map due to end-of-input

### ISSUE THREAD

**Issue by caverdude** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#16]
https://github.com/caverdude/java/blob/master/FullStackSpringBootReact-1-ch4-jwtauth.zip

I get something like this when accessing localhost:8080/login    btw I am using H2 not MySQL that a problem? H2 worked fine with database auth which was where I started from when adding this JWT code. I may go back and try the MySQL later. I'm using Idea not Eclipse also. 

com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (org.apache.catalina.connector.CoyoteInputStream); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344) ~[ja

**Comment by caverdude** [comment]
never mind, I get it, it does this because you didn't send login credentials in body.. so it works with rest client in firefox and I get token back, but when I try to do a get with token I get 403 denied no matter what url I try.

**Comment by caverdude** [comment]
ok, never mind it totally works now. I did something and screwed up the /api endpoint so every time I tried the jwt token with /api/cars or /api I got 404 or 403,  but when I did / or /cars I got json data.

**Comment by gaurav-packt** [comment]
Closing the issue as it has been resolved
