### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by hfye** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#5]
Chapter 10 code got error "Access to fetch at 'http://localhost:8080/api/cars' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

**Comment by juhahinkula** [comment]
There is bug in the book code in chapter 4 that cause this. But the id code is correct in the GitHub repository. This fix can be found also from the book's errata page https://www.packtpub.com/books/content/support/33796
