### ISSUE TITLE
Chapter-04 code REST API issue

### ISSUE THREAD

**Issue by vikramkhatri** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#6]
Hi, 

I am trying to run `Chapter-04` code to learn REST API using 
```
 <dependency>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>
```

When I try : localhost:8080/api

It shows this error:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Dec 10 20:14:29 PST 2018
There was an unexpected error (type=Forbidden, status=403).
Access Denied
```

Can you please fix the code or suggest how to go about this? The book is well written and I am enjoying it.

My environment is: 
```
$ mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: C:\mvn
Java version: 1.8.0_191-1-redhat, vendor: Oracle Corporation, runtime: C:\Java\jdk-1.8.0.191\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

The Spring Boot version: :: Spring Boot ::        (v2.0.1.RELEASE)

[logs.txt](https://github.com/PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React/files/2665958/logs.txt)

**Comment by juhahinkula** [comment]
This might be the reason. This can be found from the book Errata page https://www.packtpub.com/books/content/support/33796

Chapter 4, Page 88 - Step 5, Type: Code

This: 
@Override
protected void configure(HttpSecurity http) throws Exception {
http.cors().and().authorizeRequests()
 
It should be:
@Override
protected void configure(HttpSecurity http) throws Exception {
http.csrf().disable().cors().and().authorizeRequests()

**Comment by juhahinkula** [comment]
Closed
