### ISSUE TITLE
column name is desc

### ISSUE THREAD

**Issue by cubu** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#8]
I stuck at this error for 30 minutes.

In chapter 2, when author talk about @Column annotation, he give out the sample as below:
`@Column(name="desc", nullable=false, length=512)`
`private String description`

This code in fact dont include in the code base, just  an example. However, when I add description to the Car model with the code above, it didnt work.

The reason is that 'desc' is a reserved keyword for MariaDB (among others). We need to change it to description (for example), by that the application can run.

**Comment by juhahinkula** [comment]
Thank you. I will correct this to next edition.
