### ISSUE TITLE
Security config

### ISSUE THREAD

**Issue by taksoidet** [PacktPublishing/Hands-On-Full-Stack-Development-with-Spring-Boot-2.0-and-React#9]
When you switch to JWT authorization you no need more to keep a cookie according to stateless principle of REST. You need to add some changes to SecurityConfig.java file like this 
@Override
    protected void configure(HttpSecurity http) throws Exception {
        http.**sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)**.and().
                csrf().disable().cors().and().authorizeRequests()
                .antMatchers(HttpMethod.POST, "/login").permitAll()
                .anyRequest().authenticated()
                .and()
                .addFilterBefore(new LoginFilter("/login", authenticationManager()),
                        UsernamePasswordAuthenticationFilter.class)
                .addFilterBefore(new AuthenticationFilter(),
                        UsernamePasswordAuthenticationFilter.class);
    }

![изображение](https://user-images.githubusercontent.com/37811810/58755011-cb042580-84e3-11e9-8230-1e40d4965e95.png)

**Comment by juhahinkula** [comment]
Thanks, I will check this out
